package Restaurant.View.Form.WarehouseStaff;

import Restaurant.Controller.Service.ServiceStaffWarehouse;
import Restaurant.Model.Modelngredient;
import Restaurant.View.Component.WarehouseStaff.FormWareHouseStaff;
import Restaurant.View.Component.WarehouseStaff.SimpleForm;
import Restaurant.View.Swing.Login.ButtonOutLine;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

public class Table_InsertAndUpdate_Ingredient extends SimpleForm {

    private ServiceStaffWarehouse service;
    private Modelngredient data;
    private boolean insert;  //Thêm hay sửa
    public Table_InsertAndUpdate_Ingredient(Modelngredient data) {
        this.data = data;
        initComponents();
        initFormData();
    }

    public void initFormData() {
        service = new ServiceStaffWarehouse();
        if (data == null) {
            insert = true;
            lbTitle.setText("THÊM NGUYÊN LIỆU");
            data = new Modelngredient();
            initID_NL();
        } else {
            insert = false;
            lbTitle.setText("SỬA NGUYÊN LIỆU");
            setData(data);
        }
    }

    public void setData(Modelngredient data) {
        txtMaNL.setText(data.getiD_Ingr() + "");
        txtTenNL.setText(data.getNameIngre());
        txtDonGia.setText(data.getPrice() + "");
        cboDVT.setSelectedItem(data.getUnit());
        txtSoLuongTon.setText(data.getQuantityInStock() + "");
    }

    public void initID_NL() {
        try {
            data.setiD_Ingr(service.getNextID_NL());
            txtMaNL.setText(data.getiD_Ingr() + "");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public void setBtnHuy(ButtonOutLine btnHuy) {
        this.btnHuy = btnHuy;
    }

    public void setBtnXacNhan(ButtonOutLine btnXacNhan) {
        this.btnXacNhan = btnXacNhan;
    }

    public ButtonOutLine getBtnHuy() {
        return btnHuy;
    }

    public ButtonOutLine getBtnXacNhan() {
        return btnXacNhan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMaNL = new Restaurant.View.Swing.Dashboard.MyTextField();
        txtTenNL = new Restaurant.View.Swing.Dashboard.MyTextField();
        txtDonGia = new Restaurant.View.Swing.Dashboard.MyTextField();
        cboDVT = new javax.swing.JComboBox<>();
        txtSoLuongTon = new Restaurant.View.Swing.Dashboard.MyTextField();
        btnHuy = new Restaurant.View.Swing.Login.ButtonOutLine();
        btnXacNhan = new Restaurant.View.Swing.Login.ButtonOutLine();
        lbMessage3 = new javax.swing.JLabel();
        lbMessage4 = new javax.swing.JLabel();
        lbMessage1 = new javax.swing.JLabel();
        lbMessage2 = new javax.swing.JLabel();
        lbMessage5 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        txtMaNL.setEditable(false);
        txtMaNL.setEnabled(false);
        txtMaNL.setOpaque(true);

        cboDVT.setBackground(new java.awt.Color(215, 221, 232));
        cboDVT.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        cboDVT.setForeground(new java.awt.Color(83, 105, 118));
        cboDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "ml", "l" }));
        cboDVT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cboDVT.setFocusable(false);

        btnHuy.setBackground(new java.awt.Color(237, 33, 58));
        btnHuy.setForeground(new java.awt.Color(108, 91, 123));
        btnHuy.setText("Hủy");
        btnHuy.setActionCommand("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(17, 153, 142));
        btnXacNhan.setForeground(new java.awt.Color(108, 91, 123));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        lbMessage3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMessage3.setForeground(new java.awt.Color(108, 91, 123));
        lbMessage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage3.setText("Mã nguyên liệu");

        lbMessage4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMessage4.setForeground(new java.awt.Color(108, 91, 123));
        lbMessage4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage4.setText("Tên nguyên liệu");

        lbMessage1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMessage1.setForeground(new java.awt.Color(108, 91, 123));
        lbMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage1.setText("Đơn giá");

        lbMessage2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMessage2.setForeground(new java.awt.Color(108, 91, 123));
        lbMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage2.setText("Đơn vị tính");

        lbMessage5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbMessage5.setForeground(new java.awt.Color(108, 91, 123));
        lbMessage5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMessage5.setText("Số lượng tồn");

        lbTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(108, 91, 123));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Thêm nguyên liệu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMessage5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboDVT, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaNL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(116, 116, 116))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTitle)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDVT))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        handleConfirmButton();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        handleCancelButton();
    }//GEN-LAST:event_btnHuyActionPerformed
    private void txtdongiaKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9')
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }

    private void handleConfirmButton() {
        data.setNameIngre(txtTenNL.getText().trim());
        data.setPrice(Integer.parseInt(txtDonGia.getText()));
        data.setUnit(cboDVT.getSelectedItem().toString());
        data.setQuantityInStock(Integer.parseInt(txtSoLuongTon.getText()));

        try {
            if (insert) {
                service.InsertNL(data);
            } else {
                service.UpdateNL(data);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        FormWareHouseStaff.showForm(new Table_lngredientInfo());
    }

    private void handleCancelButton() {
        FormWareHouseStaff.showForm(new Table_lngredientInfo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Restaurant.View.Swing.Login.ButtonOutLine btnHuy;
    private Restaurant.View.Swing.Login.ButtonOutLine btnXacNhan;
    private javax.swing.JComboBox<String> cboDVT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMessage1;
    private javax.swing.JLabel lbMessage2;
    private javax.swing.JLabel lbMessage3;
    private javax.swing.JLabel lbMessage4;
    private javax.swing.JLabel lbMessage5;
    private javax.swing.JLabel lbTitle;
    private Restaurant.View.Swing.Dashboard.MyTextField txtDonGia;
    private Restaurant.View.Swing.Dashboard.MyTextField txtMaNL;
    private Restaurant.View.Swing.Dashboard.MyTextField txtSoLuongTon;
    private Restaurant.View.Swing.Dashboard.MyTextField txtTenNL;
    // End of variables declaration//GEN-END:variables
}
